# This is a basic workflow to help you get started with Actions

name: CI - WebScope

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ main, develop, 'feature/*' ]
  pull_request:
    branches: [ main, develop ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: {}
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Validates HTML CSS and JS
      - name: Validate HTML
        run: npx htmlhint "**/*.html"

      - name: Validate CSS
        run: npx prettier --check "css/**/*.css" || true

      - name: Validate JS
        run: npx standard "scripts/**/*.js"

    # Build docker image
      - name: Build Docker image
        run: docker build -t webscope-osciloscopio .
        
    # Test the container if works
      - name: Test run Docker container
        run: docker run --rm -p 8080:80 webscope-osciloscopio
